version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/inventarverwaltung?schema=public
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/inventarverwaltung?schema=public
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@db:5432/inventarverwaltung?schema=public
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=inventarverwaltung
      - POSTGRES_HOST=db
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - app-data:/app/data

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventarverwaltung
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  app-data:
